<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Hotels</name>
   <tag></tag>
   <elementGuidId>17e78c13-0a01-4b0c-b18e-d8f51b057ad0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.css-1dbjc4n.r-14lw9ot.r-855088.r-mm0ijv.r-dwliz8.r-1loqt21.r-6koalj.r-18u37iz.r-ymttw5.r-5njf8e.r-bnwqim.r-14qw7yl.r-1j63xyz.r-lrvibr.r-1x4r79x > div.css-901oao.r-1h9nbw7.r-16y2uox.r-1sixt3s.r-1b43r93.r-majxgm.r-1cwl3u0.r-fdjqy7.r-3s2u2q</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='__next']/div[5]/div[2]/div/div[2]/div/div/div/div/div[2]/div/div[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>fe888831-e8d2-4422-bc12-4a7e880abf18</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>dir</name>
      <type>Main</type>
      <value>auto</value>
      <webElementGuid>d562eda9-8a43-48a7-898c-8e5043f2335d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>css-901oao r-1h9nbw7 r-16y2uox r-1sixt3s r-1b43r93 r-majxgm r-1cwl3u0 r-fdjqy7 r-3s2u2q</value>
      <webElementGuid>bd58e82f-9cac-4ce8-9531-5ba5d16dbace</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Hotels</value>
      <webElementGuid>e811dcdf-3f84-4664-b075-05906a47c9cf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/div[@class=&quot;css-1dbjc4n r-1jgb5lz r-xiad99 r-16k0tzm&quot;]/div[@class=&quot;css-1dbjc4n&quot;]/div[@class=&quot;css-1dbjc4n r-14lw9ot r-kdyh1x r-1yos0t3 r-bztko3 r-184en5c&quot;]/div[@class=&quot;css-1dbjc4n r-kdyh1x r-pezta&quot;]/div[@class=&quot;css-1dbjc4n r-6koalj r-18u37iz r-12w9sp&quot;]/div[@class=&quot;css-1dbjc4n r-391gc0 r-1wh2hl7 r-o8yidv r-1udh08x&quot;]/div[@class=&quot;css-1dbjc4n r-u8s1d r-13qz1uu&quot;]/div[@class=&quot;css-1dbjc4n r-391gc0&quot;]/div[@class=&quot;css-1dbjc4n r-1loqt21 r-1otgn73 r-1x4r79x&quot;]/div[@class=&quot;css-1dbjc4n r-14lw9ot r-855088 r-mm0ijv r-dwliz8 r-1loqt21 r-6koalj r-18u37iz r-ymttw5 r-5njf8e r-bnwqim r-14qw7yl r-1j63xyz r-lrvibr r-1x4r79x&quot;]/div[@class=&quot;css-901oao r-1h9nbw7 r-16y2uox r-1sixt3s r-1b43r93 r-majxgm r-1cwl3u0 r-fdjqy7 r-3s2u2q&quot;]</value>
      <webElementGuid>169785ea-2f8f-431f-b55a-ba68805d61f7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div[5]/div[2]/div/div[2]/div/div/div/div/div[2]/div/div[2]</value>
      <webElementGuid>cac1d4dd-d461-4c35-b362-7d8e9493b1f8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Flights'])[1]/following::div[5]</value>
      <webElementGuid>00903495-b317-47b7-9e62-690d54531677</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='See more promos'])[1]/following::div[21]</value>
      <webElementGuid>7592b866-3ea4-47fa-bc30-8a92d7234d95</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Holiday Stays'])[1]/preceding::div[2]</value>
      <webElementGuid>c539aff5-d7db-4193-838f-d194bd2abe0d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Xperience'])[1]/preceding::div[6]</value>
      <webElementGuid>bb6448b7-edc5-485a-9d43-d73cb9200a98</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Hotels']/parent::*</value>
      <webElementGuid>df84f564-5891-46f5-8728-5beb939d5b57</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/div/div[2]/div/div[2]</value>
      <webElementGuid>78e2e1a9-2ae3-4676-a7b1-e30ff9da5f4b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Hotels' or . = 'Hotels')]</value>
      <webElementGuid>733e9c69-980a-4f8e-b6d4-e47b669146c5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
