<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Title_Deluxe Balcony City View</name>
   <tag></tag>
   <elementGuidId>b4eff878-249f-408e-9d57-fccdabf6e82f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.css-901oao.r-1sixt3s.r-1i10wst.r-b88u0q.r-135wba7.r-fdjqy7</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//body/div[@id='__next']/div[5]/div[1]/div[1]/div[8]/div[3]/div[1]/div[1]/div[2]/div[1]/div[3]/div[1]/div[1]/div[1]/div[1]/div[1]/div[1]/div[1]/div[1]/div[1]
</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>edccd3d8-0544-4b92-9660-122798534da1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>dir</name>
      <type>Main</type>
      <value>auto</value>
      <webElementGuid>948b0203-8c87-4bf9-a2b5-8eba80fa54a8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>css-901oao r-1sixt3s r-1i10wst r-b88u0q r-135wba7 r-fdjqy7</value>
      <webElementGuid>ab06c712-d4f3-46c5-aa5b-0fece6d860b2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Deluxe Balcony City View</value>
      <webElementGuid>e0f2888b-fd8f-4654-916d-166f095a5ae7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/div[@class=&quot;css-1dbjc4n&quot;]/div[@class=&quot;css-1dbjc4n r-1jgb5lz r-1r5su4o r-uwe93p r-pezta&quot;]/div[@class=&quot;css-1dbjc4n r-1oszu61 r-eqz5dr&quot;]/div[@class=&quot;css-1dbjc4n&quot;]/div[@class=&quot;css-1dbjc4n r-1oszu61 r-eqz5dr&quot;]/div[@class=&quot;css-1dbjc4n&quot;]/div[@class=&quot;css-1dbjc4n&quot;]/div[@class=&quot;css-1dbjc4n r-mabd2g r-ttdzmv r-gtdqiz r-8fdsdq&quot;]/div[@class=&quot;css-1dbjc4n r-391gc0 r-o8yidv r-ir6n1k r-ymttw5 r-1f1sjgu&quot;]/div[@class=&quot;css-901oao r-1sixt3s r-1i10wst r-b88u0q r-135wba7 r-fdjqy7&quot;]</value>
      <webElementGuid>2a75899d-b018-4d64-9020-c54567d9a4cd</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div[5]/div/div/div[8]/div[3]/div/div/div/div/div</value>
      <webElementGuid>7c9ed0c0-5b6f-4b37-b45f-1eff1455db04</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Guests and Rooms'])[1]/following::div[13]</value>
      <webElementGuid>bd91a873-6a2c-4578-b205-5245f08798fe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Duration'])[1]/following::div[26]</value>
      <webElementGuid>64d5242d-b753-409c-8963-b9ecce20867e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Balcony / Terrace'])[1]/preceding::div[13]</value>
      <webElementGuid>da0ef75d-27d6-4780-831b-6c26fd194e0d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Refrigerator'])[1]/preceding::div[17]</value>
      <webElementGuid>2a4f2ad2-9233-4631-a8d7-64b141698bae</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Deluxe Balcony City View']/parent::*</value>
      <webElementGuid>6758eb79-6e92-4f43-8929-784344331b2a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[8]/div[3]/div/div/div/div/div</value>
      <webElementGuid>74a6fdde-6eca-4ebf-a4e6-801a8fc7008b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Deluxe Balcony City View' or . = 'Deluxe Balcony City View')]</value>
      <webElementGuid>f6309749-e7cc-4d0a-8708-5bc2b2bb6105</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
