<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_High Floor</name>
   <tag></tag>
   <elementGuidId>9f21e5d5-ab66-4884-bbdc-696b1ec549a2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='__next']/div[2]/div/div/div[3]/div/div[4]/div[2]/div[2]/div/div/div[3]/div/div/div/div[2]/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>c0caa462-8f57-40ba-a6e5-82f619595627</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>dir</name>
      <type>Main</type>
      <value>auto</value>
      <webElementGuid>72e12bf4-aea0-4c07-8297-aa64eeb98e39</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>css-901oao r-1sixt3s r-ubezar r-majxgm r-135wba7 r-1m7fwk6 r-fdjqy7</value>
      <webElementGuid>ec16ebf7-04e0-4443-94a7-205d23f93558</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-testid</name>
      <type>Main</type>
      <value>tvat-requestOption</value>
      <webElementGuid>f3a8defc-1f87-4357-8691-a905b8fc2c76</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>High Floor</value>
      <webElementGuid>a3989733-0a4e-4141-9f18-3407e3c54beb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/div[@class=&quot;css-1dbjc4n r-391gc0&quot;]/div[@class=&quot;css-1dbjc4n r-1jgb5lz r-1r5su4o r-uwe93p&quot;]/div[@class=&quot;css-1dbjc4n&quot;]/div[@class=&quot;css-1dbjc4n r-1habvwh r-18u37iz&quot;]/div[@class=&quot;css-1dbjc4n r-dta0w2&quot;]/div[@class=&quot;css-1dbjc4n r-zd98yo&quot;]/div[@class=&quot;css-1dbjc4n r-14lw9ot r-kdyh1x r-da5iq2 r-bztko3 r-136ojw6&quot;]/div[@class=&quot;css-1dbjc4n r-xyw6el&quot;]/div[@class=&quot;css-1dbjc4n r-1g40b8q&quot;]/div[@class=&quot;css-1dbjc4n r-18u37iz r-1w6e6rj&quot;]/div[@class=&quot;css-1dbjc4n r-1t2qqvi r-16y2uox r-1wbh5a2 r-1s2bzr4&quot;]/div[@class=&quot;css-1dbjc4n r-136ojw6&quot;]/div[@class=&quot;css-1dbjc4n r-1loqt21 r-1otgn73 r-1i6wzkk r-lrvibr&quot;]/div[@class=&quot;css-1dbjc4n r-1awozwy r-18u37iz r-t60dpp&quot;]/div[@class=&quot;css-1dbjc4n r-13awgt0 r-eqz5dr r-19u6a5r&quot;]/div[@class=&quot;css-901oao r-1sixt3s r-ubezar r-majxgm r-135wba7 r-1m7fwk6 r-fdjqy7&quot;]</value>
      <webElementGuid>323a4c91-8249-4f37-a0f2-559cb343bd6f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div[2]/div/div/div[3]/div/div[4]/div[2]/div[2]/div/div/div[3]/div/div/div/div[2]/div</value>
      <webElementGuid>b8b70567-f8a8-453c-b00d-4f058a5358d3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Connecting Rooms'])[1]/following::div[12]</value>
      <webElementGuid>af1e2f60-a60b-4cff-ae51-4d3ebabb6f0d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Non-smoking Room'])[1]/following::div[24]</value>
      <webElementGuid>d9567605-c20b-469d-8541-a52be87e7a5b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Bed Type'])[1]/preceding::div[7]</value>
      <webElementGuid>c9131706-1092-422f-85f2-72e0cc7d808c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Check-in Time'])[1]/preceding::div[39]</value>
      <webElementGuid>18cf809d-c2d1-4785-8033-0981ffa79821</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='High Floor']/parent::*</value>
      <webElementGuid>dbaaa1c3-014c-433e-ae0c-3265dc253d8f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/div/div/div[3]/div/div/div/div[2]/div</value>
      <webElementGuid>882c20a1-99eb-418c-86cb-211bded7efef</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'High Floor' or . = 'High Floor')]</value>
      <webElementGuid>b7a0975b-03b1-4095-9319-a8bc07d8a2cc</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
