<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Special request_css-9pa8cd</name>
   <tag></tag>
   <elementGuidId>a2564123-37ec-46d4-96d4-1e73b65781ce</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>img.css-9pa8cd</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='__next']/div[2]/div/div/div[3]/div/div[4]/div[2]/div[2]/div/div/div/div/div/div/div/div[3]/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>87c26e99-ec12-4b35-800e-c581537b6ce9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>draggable</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>403be63f-74f3-4159-a15b-a51b036c4ecb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://d1785e74lyxkqq.cloudfront.net/_next/static/v2/d/dec47c4e28c7e02370e469ab61f05ea6.png</value>
      <webElementGuid>720f6175-3acf-48a0-a33f-51e477e6789e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>css-9pa8cd</value>
      <webElementGuid>4fc2806f-46a4-412d-b356-df656f62e6c0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/div[@class=&quot;css-1dbjc4n r-391gc0&quot;]/div[@class=&quot;css-1dbjc4n r-1jgb5lz r-1r5su4o r-uwe93p&quot;]/div[@class=&quot;css-1dbjc4n&quot;]/div[@class=&quot;css-1dbjc4n r-1habvwh r-18u37iz&quot;]/div[@class=&quot;css-1dbjc4n r-dta0w2&quot;]/div[@class=&quot;css-1dbjc4n r-zd98yo&quot;]/div[@class=&quot;css-1dbjc4n r-14lw9ot r-kdyh1x r-da5iq2 r-bztko3 r-136ojw6&quot;]/div[@class=&quot;css-1dbjc4n r-xyw6el&quot;]/div[@class=&quot;css-1dbjc4n r-1g40b8q&quot;]/div[@class=&quot;css-1dbjc4n r-18u37iz r-1w6e6rj&quot;]/div[@class=&quot;css-1dbjc4n r-1t2qqvi r-16y2uox r-1wbh5a2 r-1s2bzr4&quot;]/div[@class=&quot;css-1dbjc4n r-136ojw6&quot;]/div[@class=&quot;css-1dbjc4n r-1loqt21 r-1otgn73 r-1i6wzkk r-lrvibr&quot;]/div[@class=&quot;css-1dbjc4n r-1awozwy r-18u37iz r-t60dpp&quot;]/div[@class=&quot;css-1dbjc4n r-1awozwy r-kdyh1x r-rs99b7 r-z80fyv r-1777fci r-1dumxj3 r-1udh08x r-19wmn03&quot;]/div[@class=&quot;css-1dbjc4n r-1mlwlqe r-1udh08x r-417010&quot;]/img[@class=&quot;css-9pa8cd&quot;]</value>
      <webElementGuid>e77db583-8ab1-46ea-ae7b-db2d6cf84d11</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div[2]/div/div/div[3]/div/div[4]/div[2]/div[2]/div/div/div/div/div/div/div/div[3]/img</value>
      <webElementGuid>6c8c9c51-e969-4837-a88d-eb6aff03df24</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[contains(@src,'https://d1785e74lyxkqq.cloudfront.net/_next/static/v2/d/dec47c4e28c7e02370e469ab61f05ea6.png')]</value>
      <webElementGuid>4f48e303-61da-49b9-83e1-64c5149f880b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/img</value>
      <webElementGuid>27934f99-c07a-4599-ab02-768150241916</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://d1785e74lyxkqq.cloudfront.net/_next/static/v2/d/dec47c4e28c7e02370e469ab61f05ea6.png']</value>
      <webElementGuid>3bd4dc24-0946-4271-bb0a-2fe9285624e0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
