<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btn_Alfamart</name>
   <tag></tag>
   <elementGuidId>2d9bbbcd-fad0-49f7-ae55-32e3231a3b3f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.css-1dbjc4n.r-hr69ez.r-1loqt21.r-16l9doz.r-1guathk.r-rjfia.r-1otgn73.r-1i6wzkk.r-lrvibr.r-13qz1uu > div.css-1dbjc4n.r-1awozwy.r-13awgt0.r-18u37iz.r-1wtj0ep.r-mk0yit > div.css-1dbjc4n.r-1awozwy.r-13awgt0.r-18u37iz.r-1h0z5md</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[contains(text(),'Alfamart')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>5cb11597-5744-464b-9b9a-d72cccc57c6c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>css-1dbjc4n r-1awozwy r-13awgt0 r-18u37iz r-1h0z5md</value>
      <webElementGuid>c42a581c-4291-4476-bce0-3435a548a4fc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Alfamart</value>
      <webElementGuid>1dd15eb7-809b-483b-a255-4781423be391</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/div[@class=&quot;css-1dbjc4n&quot;]/div[@class=&quot;css-1dbjc4n&quot;]/div[@class=&quot;css-1dbjc4n r-mabd2g&quot;]/div[@class=&quot;css-1dbjc4n r-ywje51 r-zd98yo r-uwe93p&quot;]/div[@class=&quot;css-1dbjc4n r-1habvwh r-13awgt0 r-18u37iz&quot;]/div[@class=&quot;css-1dbjc4n r-1oszu61 r-1492nhi r-kdyh1x r-1yos0t3 r-13awgt0 r-18u37iz r-1h0z5md r-1udh08x r-1wi2xyk&quot;]/div[@class=&quot;css-1dbjc4n r-1pi2tsx&quot;]/div[@class=&quot;css-1dbjc4n r-1492nhi r-6t5ypu r-kicko2 r-5vf7qs r-184en5c&quot;]/div[@class=&quot;css-1dbjc4n&quot;]/div[@class=&quot;css-1dbjc4n r-hr69ez r-1loqt21 r-16l9doz r-1guathk r-rjfia r-1otgn73 r-1i6wzkk r-lrvibr r-13qz1uu&quot;]/div[@class=&quot;css-1dbjc4n r-1awozwy r-13awgt0 r-18u37iz r-1wtj0ep r-mk0yit&quot;]/div[@class=&quot;css-1dbjc4n r-1awozwy r-13awgt0 r-18u37iz r-1h0z5md&quot;]</value>
      <webElementGuid>68672579-4ff1-48cc-81c4-a616659c7dd8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div/div[2]/div/div[2]/div/div/div/div/div/div[5]/div/div</value>
      <webElementGuid>cdb4c1bc-d53d-4c0b-824f-f5efe027f95a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ATM'])[1]/following::div[3]</value>
      <webElementGuid>ff712ff0-88c4-453e-b2e0-598958c3b093</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Bank Transfer'])[1]/following::div[7]</value>
      <webElementGuid>c1de0330-3a68-477a-89d6-06cd7f976ab4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Indomaret'])[1]/preceding::div[2]</value>
      <webElementGuid>5f12fb9f-b577-4bf3-b91e-faffda321a19</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div/div</value>
      <webElementGuid>7290bf1d-db23-4251-b099-6144c183e5ba</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Alfamart' or . = 'Alfamart')]</value>
      <webElementGuid>057c7826-6c97-4aa8-b23a-13fc302078ee</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
