<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>title_THE 1O1 Yogyakarta Tugu Hotel</name>
   <tag></tag>
   <elementGuidId>93723294-d683-4972-a4de-0c866da3be47</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>h2.css-4rbku5.css-901oao.r-1sixt3s.r-adyw6z.r-b88u0q.r-135wba7.r-1ow6zhx.r-fdjqy7</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//h2[contains(text(),'THE 1O1 Yogyakarta Tugu Hotel')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h2</value>
      <webElementGuid>22e0660c-2f2e-48c0-8bbf-8bb4004e1495</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-level</name>
      <type>Main</type>
      <value>2</value>
      <webElementGuid>e73541b3-a2d1-4689-954b-479561d07948</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>dir</name>
      <type>Main</type>
      <value>auto</value>
      <webElementGuid>6eb89c56-7de6-428d-8a54-56632b955b63</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>heading</value>
      <webElementGuid>a54b86e2-2d4e-4473-904a-36d82ab5dcd1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>css-4rbku5 css-901oao r-1sixt3s r-adyw6z r-b88u0q r-135wba7 r-1ow6zhx r-fdjqy7</value>
      <webElementGuid>1306d53b-0e15-4128-91b9-6955b6669ddb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>THE 1O1 Yogyakarta Tugu Hotel</value>
      <webElementGuid>6784b499-d636-478d-a9ac-adb0f9e541cd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/div[@class=&quot;css-1dbjc4n r-391gc0&quot;]/div[@class=&quot;css-1dbjc4n r-1jgb5lz r-1r5su4o r-uwe93p&quot;]/div[@class=&quot;css-1dbjc4n&quot;]/div[@class=&quot;css-1dbjc4n r-18u37iz&quot;]/div[@class=&quot;css-1dbjc4n&quot;]/div[@class=&quot;css-1dbjc4n&quot;]/div[@class=&quot;css-1dbjc4n r-14lw9ot r-kdyh1x r-da5iq2 r-1udh08x r-1l7z4oj r-ymttw5 r-1ygmrgt&quot;]/div[@class=&quot;css-1dbjc4n r-18u37iz&quot;]/div[@class=&quot;css-1dbjc4n r-k200y r-13awgt0 r-1ow6zhx&quot;]/div[@class=&quot;css-1dbjc4n r-19u6a5r r-1s2bzr4&quot;]/div[@class=&quot;css-1dbjc4n r-18u37iz&quot;]/div[@class=&quot;css-1dbjc4n r-13awgt0 r-13qz1uu&quot;]/div[@class=&quot;css-1dbjc4n&quot;]/h2[@class=&quot;css-4rbku5 css-901oao r-1sixt3s r-adyw6z r-b88u0q r-135wba7 r-1ow6zhx r-fdjqy7&quot;]</value>
      <webElementGuid>f0936f31-c6d8-45e7-ac18-9b909d1e9e35</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div[2]/div/div/div[3]/div/div/div/div/div[2]/div/div/div[2]/div/h2</value>
      <webElementGuid>921c87fb-46b9-445f-9f91-0c9d47921c92</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Please review your booking details before continuing to payment'])[1]/following::h2[1]</value>
      <webElementGuid>974af219-68fb-4dba-83eb-64848198f50e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Please Review Your Booking'])[1]/following::h2[1]</value>
      <webElementGuid>129c0899-6753-4902-a7c3-957fc38e7d92</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Check-in'])[1]/preceding::h2[1]</value>
      <webElementGuid>5a9b1e8b-50d7-4358-bfc8-57277b9f7be9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='From 14:00'])[1]/preceding::h2[1]</value>
      <webElementGuid>0ae740da-e413-482e-b4ac-c7a9bc465954</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='THE 1O1 Yogyakarta Tugu Hotel']/parent::*</value>
      <webElementGuid>a88d28bb-7cd4-4add-a164-5f325d36fb33</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//h2</value>
      <webElementGuid>e5be0787-f162-4067-9c8c-46f317847b0c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//h2[(text() = 'THE 1O1 Yogyakarta Tugu Hotel' or . = 'THE 1O1 Yogyakarta Tugu Hotel')]</value>
      <webElementGuid>2664e461-ee10-40fb-99a9-c8b4abdd339a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
